import { User } from './models/userModel'
import { Product } from './models/productModel'
import bcrypt from 'bcryptjs'
export const sampleProducts: Product[] = [
  // {
  //   name: 'Nike Slim shirt',
  //   slug: 'nike-slim-shirt',
  //   category: 'Shirts',
  //   image: '../images/p1.jpg',
  //   price: 120,
  //   countInStock: 10,
  //   brand: 'Nike',
  //   rating: 4.5,
  //   numReviews: 10,
  //   description: 'high quality shirt',
  // },
  // {
  //   name: 'Adidas Fit Shirt',
  //   slug: 'adidas-fit-shirt',
  //   category: 'Shirts',
  //   image: '../images/p2.jpg',
  //   price: 100,
  //   countInStock: 20,
  //   brand: 'Adidas',
  //   rating: 4.0,
  //   numReviews: 10,
  //   description: 'high quality product',
  // },
  // {
  //   name: 'Lacoste Free Pants',
  //   slug: 'lacoste-free-pants',
  //   category: 'Pants',
  //   image: '../images/p3.jpg',
  //   price: 220,
  //   countInStock: 0,
  //   brand: 'Lacoste',
  //   rating: 4.8,
  //   numReviews: 17,
  //   description: 'high quality product',
  // },
  // {
  //   name: 'Nike Slim Pant',
  //   slug: 'nike-slim-pant',
  //   category: 'Pants',
  //   image: '../images/p4.jpg',
  //   price: 78,
  //   countInStock: 15,
  //   brand: 'Nike',
  //   rating: 4.5,
  //   numReviews: 14,
  //   description: 'high quality product',
  // },
  {
    name: 'Nike Slim Shirt',
    slug: 'Nike Slim Shirt',
    category: 'Shirts',
    image: '/images/p5.jpg',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'Adidas Fit Shirt',
    category: 'Shirts',
    image: '/images/p6.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Lacoste Free Shirt',
    slug: 'Lacoste Free Shirt',
    category: 'Shirts',
    image: '/images/p7.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'high quality product',
  },
  {
    name: 'Nike Slim Pant',
    slug: 'Nike Slim Pant',
    category: 'Pants',
    image: '/images/p8.jpg',
    price: 78,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 14,
    description: 'high quality product',
  },
  {
    name: 'Puma Slim Pant',
    slug: 'Puma Slim Pant',
    category: 'Pants',
    image: '/images/p9.jpg',
    price: 65,
    countInStock: 5,
    brand: 'Puma',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    name: 'Adidas Fit Pant',
    slug: 'Adidas Fit Pant',
    category: 'Pants',
    image: '/images/p10.jpg',
    price: 139,
    countInStock: 12,
    brand: 'Adidas',
    rating: 4.5,
    numReviews: 15,
    description: 'high quality product',
  },
]

export const sampleUsers: User[] = [
  {
    name: 'Bhanudas',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: true,
  },
  {
    name: 'Bhushan',
    email: 'user@example.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
]
